version: "3.8"
services:
  app:
    stdin_open: true
    container_name: to-the-moon
    image: to-the-moon
    build:
      context: .
      # for deployment on production, use the following:
      dockerfile: dockerfile.prod
      # for deployment on local, use the following:
      # dockerfile: dockerfile.dev
    volumes:
      # - /app/node_modules
      - .:/app
    ports:
      - 5173:5173
networks:
  default:
      name: yadom
      external: true
volumes:
  dependencies:
    driver: local
